export enum ActionType {
  LOAD_MERCHANT_CATEGORIES = 'MERCHANT/LOAD_MERCHANT_CATEGORIES',
  LOAD_MERCHANT_CATEGORIES_SUCCESS = 'MERCHANT/LOAD_MERCHANT_CATEGORIES_SUCCESS',
  LOAD_CURRENT_MERCHANT = 'MERCHANT/LOAD_CURRENT_MERCHANT',
  LOAD_CURRENT_MERCHANT_SUCCESS = 'MERCHANT/LOAD_CURRENT_MERCHANT_SUCCESS',
  LOAD_MERCHANT_SEARCH_LIST = 'MERCHANT/LOAD_MERCHANT_SEARCH_LIST',
  LOAD_MERCHANT_SEARCH_LIST_SUCCESS = 'MERCHANT/LOAD_MERCHANT_SEARCH_LIST_SUCCESS',
  END_EDIT = 'MERCHANT/END_EDIT',
}
